### ISSUE TITLE
Anyone can fake a proof

### ISSUE THREAD

**Issue by grzegorz225** [aeternity/elixir-merkle-patricia-tree#11]
The proof verification logic does not check whether the hashes are correct - It is trivial to fake a proof. I added a test demonstrating this to the GH-9 branch.

Failing test on the GH-9 branch:
1) test Check whether we actually check the hashes ;) (MerklePatriciaTreeProofTest)
     test/proof_test.exs:67
     Assertion with == failed
     code:  assert false == Proof.verify_proof(bogus_key, bogus_val, trie.root_hash(), bogus_proof)
     left:  false
     right: true
     stacktrace:
       test/proof_test.exs:79: (test)

**Comment by cytadela8** [comment]
Closed by #12

**Comment by grzegorz225** [comment]
Fixed in PR-9
